# ============================================================
#  FitStore — application.properties
# ============================================================

# ── Servidor ────────────────────────────────────────────────
server.port=8080

# ── MySQL ───────────────────────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3306/fitstore_db?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=fitstore2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ── Redis (Cache-Aside — RNF-01: stock < 1 segundo) ────────
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# ── RabbitMQ (notificaciones asíncronas) ───────────────────
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

fitstore.rabbitmq.queue=fitstore.pedidos.queue
fitstore.rabbitmq.exchange=fitstore.exchange
fitstore.rabbitmq.routing-key=pedido.confirmado

# ── JWT ─────────────────────────────────────────────────────
fitstore.jwt.secret=FitStore2026SuperSecretKeyParaJWTMustBe256BitsLong!!
fitstore.jwt.expiration=86400000

# ── CORS ────────────────────────────────────────────────────
fitstore.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:5500

# ── Logging ─────────────────────────────────────────────────
logging.level.com.fitstore=INFO
logging.level.org.springframework.security=WARN
